# Generated by Django 2.1.4 on 2019-06-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='duration',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
