# Generated by Django 2.1.4 on 2019-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activities_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='date',
            field=models.DateField(),
        ),
    ]
