# Generated by Django 2.1.4 on 2019-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20190630_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
